In [1]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a2d = a.reshape((2,3))
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
a2d[0]

array([1, 2, 3])

In [20]:
a3d = np.arange(0,12).reshape((2,2,3))
a3d

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [24]:
a3d[0]

array([[0, 1, 2],
       [3, 4, 5]])